"""A deterministic provider with no network and no credential.

Two purposes, both of them load-bearing:

* **Tests.** Every AI route can be exercised end to end without a network, a key,
  or a bill. The output is a pure function of the request, so a test asserting on
  the exact text is asserting on something stable.
* **Offline development and demos.** ``AI_PROVIDER=fake`` gives a working UI on a
  laptop with no provider account, which is the only way the panels can be built
  against before a real provider exists.

The reason this lives in the shipped package rather than in ``conftest.py`` is
that a deterministic provider has to be reachable by the settings a deployment
configures. A test-only fake could not be the thing ``AI_PROVIDER`` names, and
then the registry would be exercised in a way no deployment ever exercises it.

**The text is not a real explanation and does not claim to be.** It is plainly
marked as fake output, and the API response labels every insight with the
provider that produced it, so a learner can never mistake this for a model's
words.
"""

from __future__ import annotations

from backend.app.ai.errors import AIProviderError, AIProviderTimeoutError
from backend.app.ai.provider import (
    KIND_CODE_COMPLEXITY,
    KIND_PROBLEM_EXPLANATION,
    KIND_SUBMISSION_DIAGNOSIS,
    AICompletionRequest,
    AICompletionResponse,
)

#: A source containing this marker is treated as having two nested scans, which
#: is how a test drives the complexity comparison into its "above target" branch
#: without needing a real model. It is a documented test hook, not a heuristic
#: this provider applies to anything else.
NESTED_LOOP_MARKER = "NESTED_LOOP_MARKER"

_EXPLANATION_TEMPLATE = """## What this problem asks

{fake_notice}

This explanation was produced by the deterministic `fake` provider, not by a
language model. It is fixed text chosen by the request kind, so it demonstrates
that the endpoint, the grounding, the caching, and the rendering all work
without contacting any external service.

## What a real provider would receive

- the problem statement, input and output format, constraints, and examples;
- the catalog's written editorial;
- the target time and space complexity recorded for the problem;
- an explicit instruction that the response must not state any test input,
  expected output, or hidden-case result.

It would not receive the test cases, the reference solutions, or anything else
the catalog keeps private.
"""

_DIAGNOSIS_TEMPLATE = """## What the judge reported

{fake_notice}

This diagnosis was produced by the deterministic `fake` provider, not by a
language model. The real provider is given only the stored verdict, the passed
and total case counts, the runtime and memory the judge measured, and the
judge's own error message.

## What it would never be given

- any hidden test case's input, expected output, or the program's output on it;
- any test case at all, because a judged submission stores counts and not cases;
- another learner's submissions, progress, or identity.

The grounding context for this request is the one the response lists under
`grounding`, and nothing else was sent.
"""

_COMPLEXITY_O_N_LOG_N = """{
  "time_complexity": "O(n log n)",
  "space_complexity": "O(n)",
  "reasoning": "Deterministic fake output: the request was treated as a sort-based scan."
}"""

_COMPLEXITY_O_N_SQUARED = """{
  "time_complexity": "O(n^2)",
  "space_complexity": "O(1)",
  "reasoning": "Deterministic fake output: the request carried the nested-loop marker, so it was treated as two nested scans."
}"""

_COMPLEXITY_UNDETERMINED = """{
  "time_complexity": "undetermined",
  "space_complexity": "undetermined",
  "reasoning": "Deterministic fake output: no recognised loop or scan was found in the source."
}"""

_FAKE_NOTICE = (
    "> **Generated by the deterministic `fake` provider.** This is fixed text, not "
    "a language model's answer. It exists so the feature can be exercised with no "
    "provider account configured."
)


def _explanation_text() -> str:
    return _EXPLANATION_TEMPLATE.format(fake_notice=_FAKE_NOTICE)


def _diagnosis_text() -> str:
    return _DIAGNOSIS_TEMPLATE.format(fake_notice=_FAKE_NOTICE)


def _complexity_text(request: AICompletionRequest) -> str:
    if NESTED_LOOP_MARKER in request.user:
        return _COMPLEXITY_O_N_SQUARED
    if "while" in request.user or "for" in request.user:
        return _COMPLEXITY_O_N_LOG_N
    return _COMPLEXITY_UNDETERMINED


class FakeAIProvider:
    """A provider that answers from a fixed table and never touches a network.

    ``responses`` overrides the default text per kind, which is how a test drives
    a specific provider outcome without a subclass. ``error`` makes every call
    raise, which is how the 502 and 504 mappings are exercised against the real
    routes rather than against a stubbed exception handler.
    """

    def __init__(self, settings=None, *, responses: dict[str, str] | None = None, error: Exception | None = None) -> None:
        self.settings = settings
        self.name = "fake"
        #: Never ``AI_MODEL``. Every insight row stores the model that wrote it,
        #: so borrowing the name of the configured production model here would
        #: permanently attribute fixed strings to a model that never saw the
        #: request.
        self.model = "fake-deterministic"
        self.responses = dict(responses or {})
        self.error = error
        #: Every request this provider was asked, in order. Useful for asserting
        #: on what was *sent*, which is how the redaction guarantees are tested.
        self.calls: list[AICompletionRequest] = []

    @property
    def configured(self) -> bool:
        """Always ``True``.

        The fake provider needs no credential and no network, so it can always
        answer. Reporting otherwise would make the registry untestable through the
        one interface a deployment actually configures.
        """
        return True

    async def complete(self, request: AICompletionRequest) -> AICompletionResponse:
        self.calls.append(request)
        if self.error is not None:
            raise self.error
        if request.kind == KIND_CODE_COMPLEXITY:
            text = self.responses.get(request.kind) or _complexity_text(request)
        elif request.kind == KIND_SUBMISSION_DIAGNOSIS:
            text = self.responses.get(request.kind) or _diagnosis_text()
        elif request.kind == KIND_PROBLEM_EXPLANATION:
            text = self.responses.get(request.kind) or _explanation_text()
        else:
            # An unknown kind is a programming error in the service, not a
            # provider problem, and answering anyway would store a mislabelled
            # insight.
            raise AIProviderError(f"No fake response is defined for insight kind {request.kind!r}.")
        return AICompletionResponse(text=text, provider=self.name, model=self.model)

    async def aclose(self) -> None:
        return None


def fake_timeout_error() -> AIProviderTimeoutError:
    """A timeout the fake provider can be configured to raise."""
    return AIProviderTimeoutError()


def fake_provider_error() -> AIProviderError:
    """A generic upstream failure the fake provider can be configured to raise."""
    return AIProviderError()


__all__ = [
    "NESTED_LOOP_MARKER",
    "FakeAIProvider",
    "fake_provider_error",
    "fake_timeout_error",
]
