import { AlertTriangle, Clock3, RotateCw, Sparkles } from "lucide-react";

import SafeMarkdown from "./SafeMarkdown";

/**
 * Shared presentation for one generated insight.
 *
 * All three panels render the same thing -- generated text, its attribution, and
 * whether it came from a model -- so they share this component rather than each
 * re-deriving what "cached", "demo output", and "provider" mean. A learner should
 * not learn three different vocabularies for the same provenance question.
 *
 * ## What this component is careful about
 *
 * **Generated text is visibly not editorial.** The catalog's own explanation
 * arrives through a different route and is labelled separately; the two are never
 * rendered in the same typography or under the same heading.
 *
 * **Demo output says so, loudly.** `is_demo_output` is the single most important
 * thing to tell a reader of generated text -- it means no model was consulted. It
 * is shown as a standing notice rather than buried in a tooltip, and it is shown
 * even when the panel is showing a cached result.
 *
 * **A cached answer is labelled as one.** It is honest and free, but it is not a
 * fresh act, and a reader deciding whether to trust an answer is entitled to know
 * which one they are looking at.
 *
 * **The model name is shown, and it comes from the row.** Not from current
 * settings: a cached answer keeps reporting the model that actually produced it,
 * which is the whole reason attribution is stored rather than looked up.
 */
export default function InsightBody({ insight, loading, error, errorStatus, onRetry, onRegenerate, children }) {
  if (loading) {
    return (
      <div className="ai-insight-state" role="status">
        <span className="spinner" />
        <span>Generating. This can take a few seconds.</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="ai-insight-state ai-insight-error" role="alert">
        <span className="feedback-icon">!</span>
        <div>
          <strong>{describeFailure(errorStatus)}</strong>
          <p>{error}</p>
        </div>
        {onRetry ? (
          <button className="button button-quiet" onClick={onRetry} type="button">
            <RotateCw size={14} /> Try again
          </button>
        ) : null}
      </div>
    );
  }

  if (!insight) return null;

  return (
    <div className="ai-insight">
      {insight.is_demo_output ? (
        <p className="ai-demo-notice">
          <AlertTriangle aria-hidden="true" size={14} /> Demo output. This deployment is running the
          deterministic <code>fake</code> provider, so this text is fixed and no language model was
          consulted.
        </p>
      ) : null}

      <SafeMarkdown text={insight.content} />

      <footer className="ai-insight-meta">
        <span className="ai-attribution">
          <Sparkles aria-hidden="true" size={13} />
          {insight.is_demo_output ? "Not from a model" : `Generated by ${insight.model}`}
        </span>
        {insight.cached ? (
          <span className="ai-cached" title="This answer was stored and no provider was called.">
            <Clock3 aria-hidden="true" size={13} /> Stored answer
          </span>
        ) : null}
        {onRegenerate ? (
          <button className="button button-quiet" disabled={loading} onClick={onRegenerate} type="button">
            <RotateCw size={13} /> Ask again
          </button>
        ) : null}
      </footer>

      {children}
    </div>
  );
}

/**
 * Name the owner of a failure, using the code the API chose.
 *
 * The API maps each status to whoever can fix it, and that mapping is information
 * worth forwarding: a 429 is the learner's own budget and will clear by itself, a
 * 503 is a deployment problem nobody in this browser can fix, and a 504 is the
 * provider being slow. All three arrive as "generation failed" otherwise.
 */
function describeFailure(status) {
  switch (status) {
    case 429:
      return "You are asking for AI too quickly";
    case 503:
      return "AI is not available on this deployment";
    case 504:
      return "The AI provider took too long";
    case 502:
      return "The AI provider could not answer";
    case 401:
      return "Sign in again to use AI";
    default:
      return "AI could not answer";
  }
}

/** `Retry-After` is not read here; the API's message already carries the wait. */
export { describeFailure };