import { AlertTriangle, Compass, Sparkles } from "lucide-react";
import { useState } from "react";

import SafeMarkdown from "../ai/SafeMarkdown";
import { degradedMessage, MENTOR_FOCUS_OPTIONS } from "./personalizationFormat";
import { useMentor } from "./useMentor";

/**
 * The AI coach: pick what to centre on, ask, and read the response.
 *
 * The backend always answers, so this panel has no "unavailable" state -- the
 * only failures shown are the platform being unreachable. When no model answered,
 * the response says why in `degraded_reason` and the panel repeats it, so
 * rules-based text is never mistaken for a model's words.
 */
export default function MentorPanel({ enabled = true }) {
  const [focus, setFocus] = useState("overview");
  const { status, guidance, error, generate } = useMentor({ enabled });

  return (
    <div className="coach-panel">
      <div className="coach-focus" role="group" aria-label="What to centre on">
        {MENTOR_FOCUS_OPTIONS.map((option) => (
          <button
            aria-pressed={option.value === focus}
            className={`button ${option.value === focus ? "button-primary" : "button-quiet"}`}
            key={option.value}
            onClick={() => setFocus(option.value)}
            type="button"
          >
            {option.label}
          </button>
        ))}
      </div>

      <button
        className="button button-primary coach-ask"
        disabled={status === "loading" || !enabled}
        onClick={() => generate(focus)}
        type="button"
      >
        <Sparkles size={15} />
        {status === "loading" ? "Asking the coach…" : status === "success" ? "Ask again" : "Ask the coach"}
      </button>

      {status === "loading" ? (
        <div className="ai-insight-state" role="status">
          <span className="spinner" />
          <span>Putting your profile in context. This can take a few seconds.</span>
        </div>
      ) : null}

      {status === "error" ? (
        <div className="ai-insight-state ai-insight-error" role="alert">
          <span className="feedback-icon">!</span>
          <div>
            <strong>Could not reach the coach</strong>
            <p>{error}</p>
          </div>
          <button className="button button-quiet" onClick={() => generate(focus)} type="button">
            Try again
          </button>
        </div>
      ) : null}

      {guidance ? <MentorResponse guidance={guidance} /> : null}

      {!guidance && status === "idle" ? (
        <p className="coach-idle-note">
          <Compass aria-hidden="true" size={14} /> Ask for a read on your recorded work. Nothing is
          generated until you do, because a model call costs from your request budget.
        </p>
      ) : null}
    </div>
  );
}

function MentorResponse({ guidance }) {
  return (
    <div className="ai-insight coach-response">
      {guidance.is_demo_output ? (
        <p className="ai-demo-notice">
          <AlertTriangle aria-hidden="true" size={14} /> Demo output. This deployment is running the
          deterministic <code>fake</code> provider, so this text is fixed and no language model was
          consulted.
        </p>
      ) : null}

      {guidance.fallback ? (
        <p className="coach-fallback-notice">
          <AlertTriangle aria-hidden="true" size={14} /> {degradedMessage(guidance.degraded_reason)}
        </p>
      ) : null}

      <SafeMarkdown text={guidance.content} />

      <footer className="ai-insight-meta">
        <span className="ai-attribution">
          <Sparkles aria-hidden="true" size={13} />
          {guidance.fallback
            ? "From your profile, by rules"
            : guidance.is_demo_output
              ? "Not from a model"
              : `Generated by ${guidance.model}`}
        </span>
        <span className="ai-cached">Focus: {guidance.focus}</span>
      </footer>
    </div>
  );
}
